[package]
name    = "dw3000"
description = "A driver for DW3000 Ultra Wide Band module implementing low and high level"
version = "0.2.0"
authors = ["Clement Pene <clement.pene@sii.fr>", "Romain Saboret <romain.saboret@sii.fr>", "BERTON Thomas <thomas.berton@sii.fr>", "RAIMBAULT Thomas <thomas.raimbault@sii.fr>"]
edition = "2021"
license = "0BSD"

[dependencies]
byte         = "0.2.4"
embedded-hal = "0.2.4"
ieee802154   = "0.5.0"
nb           = "1.0.0"
fixed        = "1.7.0"
#micromath    = "2.0.0"

[dependencies.serde]
version = "1.0.125"
default-features = false
features = ["derive"]

[dependencies.ssmarshal]
version = "1.0.0"
default-features = false

[dependencies.num_enum]
version = "0.5.1"
default-features = false

[features]
default = []
std = ["ssmarshal/std", "serde/std", "num_enum/std"]

[workspace]
members = ["example_stm32f1", "example_raspberry"]

# cargo build/run
[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true # <-
incremental = false
opt-level = 3 # <-
overflow-checks = true # <-

# cargo test
[profile.test]
codegen-units = 1
debug = 2
debug-assertions = true # <-
incremental = false
opt-level = 3 # <-
overflow-checks = true # <-

# cargo build/run --release
[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false # <-
incremental = false
# NOTE disabled to work around issue rust-lang/rust#90357
# the bug results in log messages not having location information
# (the line printed below the log message that contains the file-line location)
# lto = 'fat'
opt-level = 3 # <-
overflow-checks = false # <-

# cargo test --release
[profile.bench]
codegen-units = 1
debug = 2
debug-assertions = false # <-
incremental = false
# see comment in the profile.release section
lto = false
opt-level = 3 # <-
overflow-checks = false # <-